version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule: { interval: "weekly" }
    labels: ["dependencies", "npm"]
    open-pull-requests-limit: 10

  # Include the web app package (separate package.json) so Dependabot tracks its dependencies too
  - package-ecosystem: "npm"
    directory: "/istampit-web"
    schedule: { interval: "weekly" }
    labels: ["dependencies", "npm", "web"]
    open-pull-requests-limit: 10

  - package-ecosystem: "pip"
    directory: "/"
    schedule: { interval: "weekly" }
    labels: ["dependencies", "python"]
    open-pull-requests-limit: 10

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule: { interval: "weekly" }
    labels: ["dependencies", "ci"]
    open-pull-requests-limit: 10
