name: Action Self-Test
on:
  pull_request:
  push:
    paths:
      - 'istampit-action/**'
      - '.github/workflows/action-selftest.yml'
jobs:
  selftest:
    runs-on: ubuntu-latest
    env:
      NEXT_PUBLIC_AUTH_ORIGIN: https://auth.istampit.io
    steps:
      - name: Checkout (root only)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Fetch submodules (with PAT if available)
        env:
          SUBMODULES_TOKEN: ${{ secrets.SUBMODULES_TOKEN }}
        run: |
          if [ -n "${SUBMODULES_TOKEN}" ]; then
            git config --global url."https://${SUBMODULES_TOKEN}@github.com/".insteadOf https://github.com/
          else
            echo "No SUBMODULES_TOKEN provided; attempting public submodule fetch"
          fi
          git submodule sync --recursive
          git submodule update --init --recursive --depth=1
      - name: Create sample file
        run: echo "hello timestamp" > sample.txt
      - name: Use action to stamp (pending only)
        uses: ./istampit-action
        with:
          paths: sample.txt
      - name: List receipts
        run: ls -l sample.txt.ots || stat sample.txt.ots
      - name: Upload receipt artifact
        uses: actions/upload-artifact@v5
        with:
          name: sample-receipt
          path: sample.txt.ots
