name: Action Self-Test
on:
  pull_request:
  push:
    paths:
      - 'istampit-action/**'
      - '.github/workflows/action-selftest.yml'
jobs:
  selftest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout with submodules
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0
          token: ${{ secrets.SUBMODULES_TOKEN || github.token }}
      - name: Create sample file
        run: echo "hello timestamp" > sample.txt
      - name: Use action to stamp (pending only)
        uses: ./istampit-action
        with:
          paths: sample.txt
      - name: List receipts
        run: ls -l sample.txt.ots || stat sample.txt.ots
      - name: Upload receipt artifact
        uses: actions/upload-artifact@v4
        with:
          name: sample-receipt
          path: sample.txt.ots
