name: Security Audit (npm)

on:
  schedule:
    - cron: '0 5 * * 1' # Weekly Monday 05:00 UTC
  workflow_dispatch:

permissions:
  contents: read

jobs:
  audit:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        project:
          - '.'
          - 'istampit-web'
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v6
        with:
          node-version: '20'
      - name: Install deps
        working-directory: ${{ matrix.project }}
        run: |
          if [ -f package-lock.json ]; then npm ci; fi
      - name: npm audit (prod only)
        if: ${{ hashFiles(format('{0}/package-lock.json', matrix.project)) != '' }}
        working-directory: ${{ matrix.project }}
        run: |
          echo "Running npm audit --omit=dev in ${{ matrix.project }}"
          npm audit --omit=dev || true
