name: Auth CI
on: [push, pull_request]
defaults:
  run:
    working-directory: istampit-auth
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    env:
      NEXT_PUBLIC_AUTH_ORIGIN: https://auth.istampit.io
    steps:
      - name: Checkout (defer submodules)
        uses: actions/checkout@v4
        with:
          submodules: false
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Init submodules
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SUBMODULES_TOKEN: ${{ secrets.SUBMODULES_TOKEN }}
        run: bash .github/scripts/init-submodules.sh
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
      - name: Install
        run: npm ci || npm install
      - name: Build
        run: npm run build
