name: Auth CI
on: [push, pull_request]
defaults:
  run:
    working-directory: istampit-auth
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    env:
      NEXT_PUBLIC_AUTH_ORIGIN: https://auth.istampit.io
    steps:
      - name: Checkout (with submodules)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: recursive
          token: ${{ secrets.SUBMODULES_TOKEN }}
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
      - name: Install
        run: npm ci || npm install
      - name: Build
        run: npm run build
