name: CI (minimal) HYBRID

on:
  push:
    branches: [ main ]

jobs:
  build-web:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Verify submodules pushed
        run: |
          git submodule foreach '
            set -e
            git fetch origin
            branch=$(git rev-parse --abbrev-ref HEAD)
            if [ "$branch" = "HEAD" ]; then
              echo "INFO: $name detached at $(git rev-parse --short HEAD); skipping branch ancestry check"
            elif git merge-base --is-ancestor HEAD origin/$branch; then
              echo "OK: $name up-to-date on $branch"
            else
              echo "ERROR: Unpushed commit in $name (local HEAD not ancestor of origin/$branch)" >&2
              exit 1
            fi
          '
      - uses: actions/setup-node@v5
        with:
          node-version: '20'
          cache: 'npm'
      - name: Install deps (web only)
        working-directory: ./istampit-web
        run: npm install --no-audit --no-fund --workspaces=false
      - name: Build web (hybrid)
        working-directory: ./istampit-web
        run: npm run build

  e2e:
    runs-on: ubuntu-latest
    needs: build-web
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: actions/setup-node@v5
        with:
          node-version: '20'
          cache: 'npm'
      - name: Install deps (web only)
        working-directory: ./istampit-web
        run: npm install --no-audit --no-fund --workspaces=false
      - name: Build web (hybrid)
        working-directory: ./istampit-web
        run: npm run build
      - name: Start Next server
        working-directory: ./istampit-web
        run: |
          npm run start &
          echo "Waiting for server health endpoint..."
          for i in {1..40}; do
            if curl -sf http://localhost:3000/api/healthz > /dev/null; then
              echo "Server is up (healthz)!"; break; fi
            echo "Waiting for server... ($i)"; sleep 2;
            if [ "$i" = "40" ]; then echo "Server failed to start"; cat .next/BUILD_ID || true; exit 1; fi
          done
          curl -sf http://localhost:3000/verify > /dev/null || { echo "Verify page unreachable"; exit 1; }
      - name: Install Playwright browsers
        working-directory: ./istampit-web
        run: npx playwright install --with-deps
      - name: Run Playwright tests
        env:
          BASE_URL: http://localhost:3000
        working-directory: ./istampit-web
        run: npm run test:e2e
