name: Example iStampit Action
on: [push]
jobs:
  stamp:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run iStampit Action
        id: stamp
        uses: ./istampit-action
        with:
          paths: "README.md"
          upgrade: "true"
      - name: List receipts
        env:
          RECEIPTS: ${{ steps.stamp.outputs.receipts }}
        run: |
          echo "Receipts JSON: $RECEIPTS"
          python -c "import os,json; rs=json.loads(os.environ['RECEIPTS']); print('Receipts:\n'+'\n'.join(rs))"
      - name: Show created OTS files
        run: ls -l **/*.ots || true
