name: Scorecard supply-chain security
on:
  schedule:
    - cron: '31 2 * * 5'
  push:
    branches: [ main ]
  workflow_dispatch:
permissions:
  contents: read
  security-events: write
  id-token: write
  actions: read
  checks: read
jobs:
  analysis:
    if: ${{ !github.event.repository.private }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false
      - name: Run Scorecard analysis
        uses: ossf/scorecard-action@v2.3.3
        with:
          results_file: results.sarif
          results_format: sarif
          publish_results: false
          repo_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: scorecard-results-sarif
          path: results.sarif
      - name: Upload to code scanning
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: results.sarif
