name: Web CI
on:
  push:
    paths: ["istampit-web/**", ".github/workflows/web.yml"]
  pull_request:
    paths: ["istampit-web/**", ".github/workflows/web.yml"]
jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: istampit-web
    env:
      NEXT_PUBLIC_AUTH_ORIGIN: https://auth.istampit.io
    steps:
      - name: Checkout (root only)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Fetch submodules (with PAT if available)
        env:
          SUBMODULES_TOKEN: ${{ secrets.SUBMODULES_TOKEN }}
        run: |
          if [ -n "${SUBMODULES_TOKEN}" ]; then
            git config --global url."https://${SUBMODULES_TOKEN}@github.com/".insteadOf https://github.com/
          else
            echo "No SUBMODULES_TOKEN provided; attempting public submodule fetch"
          fi
          git submodule sync --recursive
          git submodule update --init --recursive --depth=1
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: istampit-web/package.json
      - run: npm install
      - run: npm run lint --if-present
      - run: npm test -- --run
      - name: Build (main only)
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
        run: npm run build
