name: Web CI
on:
  push:
    paths: ["istampit-web/**", ".github/workflows/web.yml"]
  pull_request:
    paths: ["istampit-web/**", ".github/workflows/web.yml"]
jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: istampit-web
    permissions:
      contents: read
    env:
      NEXT_PUBLIC_AUTH_ORIGIN: https://auth.istampit.io
    steps:
      - name: Checkout (with private submodules)
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: istampit-web/package.json
      - run: npm install
      - run: npm run lint --if-present
      - run: npm test -- --run
      - name: Build (main only)
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
        run: npm run build
